spring.application.name=gestion-solicitudes
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/solicitudes_db
spring.datasource.username=postgres
spring.datasource.password=admin
# Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Paginación:
spring.data.web.pageable.max-page-size=100

# API externa (JSONPlaceholder)
external.jsonplaceholder.base-url=https://jsonplaceholder.typicode.com
external.jsonplaceholder.connect-timeout=3s
external.jsonplaceholder.read-timeout=5s